### PR TITLE
Fixes for Linux

### PR DESCRIPTION
**Pull request by SabineWren**
for #1 
I had to make these changes to build and run on GNU+Linux. Let me know if they can be done better (I'm not very familiar with CMake or CPP). It still has some compiler warnings, and it segfaults when exiting, but I've tested that it at least runs for makeParticles, makeMCParticles, makeSphere, and makeMCSphere.

It doesn't seem to have camera controls. Is that intended?

### CODE REVIEW

**Comment by marovira** [comment]
Just as a matter of interest, are you running a 64-bit build? Because the fix you made of changing `llu` to `lu` was meant to be done on a 64-bit architecture. It could also explain the segfaults you're getting, but I'm not sure.

**Comment by SabineWren** [comment]
With GCC, CMake adds the flag march=x86-64, or with Clang -m elf_x86_64, so it's definitely a 64bit build. The error is from 2llu * current.id.
```
invalid operands to binary expression ('unsigned long long' and
      'bsoid::polygonizer::VoxelId' (aka 'tvec3<unsigned long, highp>'))
                        auto cPos = (2llu * current.id) + glm::u64vec3(1, 1, 1);
```
id has type VoxelId = PointId = glm::u64vec3.
tvec3 is the same:
```
glm/fwd.hpp:1272:	typedef tvec3<u64, highp>		highp_u64vec3;
glm/fwd.hpp:1299:	typedef highp_u64vec3			u64vec3;
```
The easy change is to make the 2 also an lu. If you want to guarantee a size of at least 64 bits, then I think the vectors need their type changed. GLM seems to use generics, so it might be possible to make u64vec3 use long long unsigned ints. However, declaring something as a VoxelId currently defaults it to long unsigned int.

**Comment by marovira** [comment]
Ok then we have an architecture difference, because on my builds it defaults to `long long unsigned int` and everything compiles... What could be done (tentatively, or until I investigate this further) is the following:

1. If it's not included already, include `atlas/core/Platform.hpp` in `Bsoid.cpp`
2. In the line where the change is, you're going to make two options. It's going to look something like this:

```c++
#if defined(ATLAS_PLATFORM_LINUX)
// Your version of the change here, using 2lu instead of 2llu
#elif defined(ATLAS_PLATFORM_WINDOWS)
// The original line here.
#endif
```

I'm going to have to look into this though, as I think it may break the larger grid resolutions if the sizes of the integers aren't wide enough, but that's going to take a while, and for now this will help you get going without breaking my builds.

**Comment by SabineWren** [comment]
The types shouldn't change between platforms, so I don't like that solution. There's no hurry to merge this. I'll look into the vec3 at some point to see why it doesn't use long long unsigned on my platform, and find a better solution for this pull request.

**Comment by marovira** [comment]
I agree they shouldn't. The only time I've seen this happen is when the builds are different, but that doesn't seem to be the case here. I really don't like that solution either, it was more of a temporary fix anyway. I'll hopefully have some time this weekend to take a look at it on my machine.

**Comment by marovira** [comment]
It's an issue with the compilers we're using. Take a look at the discussion [here.](https://stackoverflow.com/questions/4160945/c-long-long-int-vs-long-int-vs-int64-t)
It appears that my suggestion was on the right track, but I was using the wrong macros for it. I know how to fix this, but I won't be able to do anything until the weekend. The gist of the solution is that there need to be extra flags in `Platform.hpp` for each of the supported compilers (MSVC, GCC, and Clang). From there, `Bsoid.cpp` could just switch based on the compiler. That ensures that everything works as expected.

**Comment by SabineWren** [comment]
Wow, just C++ things. I look forward to seeing your approach. I came up with a working solution (hopefully for all platforms) that forces long long unsigned instead of std::uint64_t by modifying a line in glm.

atlas/external/glm/glm/detail/type_int.hpp line 27:
```
typedef long long unsigned			uint64;
```
The advantage of this approach is that it avoids messing with platform-specific definitions, which probably makes it safer. However, modifying a line in an external library makes it harder to update.

I actually prefer the fixed-width approach glm takes, as using fixed-width everywhere would prevent this type of problem in the first place. Replacing long long unsigned with std::uint64_t everywhere else might be the best solution (i.e. do what glm does in Atlas and Bsoid). However, I think that also requires replacing literal ints with contexpr function calls, as C++ doesn't have literal fixed-width ints.

**Comment by marovira** [comment]
Sorry for the long wait there... work and other things just sprung up on me. The downside with your fix is that it assumes that `uint64` must always be `long long unsigned` on every platform, which as we have seen isn't always the case. The fix that I had in mind was this: replace `2llu` with `static_cast<std::uint64_t>(2)`. This way, no matter what `uint64_t` is aliased as, it will always behave correctly.

**Comment by SabineWren** [comment]
That builds and runs well for me.

**Pull request merged**
